name: "Find changes"
description: "Outputs changed files in JSON format for downstream actions"

runs:
  using: "composite"
  steps:
    - if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - if: github.event_name == 'push'
      name: Checkout
      uses: actions/checkout@v4

    - name: Find changes
      id: changes
      shell: sh
      run: |
        "$GITHUB_ACTION_PATH/action.py"

outputs:
  array:
    description: "JSON array of changed files"
    value: ${{ steps.changes.outputs.array }}
