name: actionlint
description: Runs actionlint with color output
inputs:
  version:
    description: actionlint version to install
    required: false
    default: 1.7.7

runs:
  using: "composite"
  steps:
    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/actionlint
        key: actionlint-${{ inputs.version }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      shell: sh
      env:
        url: https://github.com/rhysd/actionlint/releases/download/v${{ inputs.version }}/actionlint_${{ inputs.version }}_linux_amd64.tar.gz
        tmp: ${{ runner.temp }}
      run: |
        curl -sSL "$url" | tar -xz -C "$tmp"
        cp "$tmp/actionlint" /usr/local/bin
    - name: Run
      shell: sh
      run: |
        actionlint -color
