name: "Compare changes"
description: "Compare changes to the paths specified in the input 'wilcard-*' GitHub Actions workflow"

inputs:
  wildcard:
    description: "Path to the wildcard configuration file"
    required: true
  changes:
    description: "JSON array of changed files (from find-changes action)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if changed files match paths
      id: wildcard
      shell: sh
      env:
        INPUT_WILDCARD: ${{ inputs.wildcard }}
        INPUT_CHANGES: ${{ inputs.changes }}
      run: |
        "$GITHUB_ACTION_PATH/action.py"

outputs:
  changed:
    description: "Boolean indicating if any changed files match paths in the wildcard file"
    value: ${{ steps.wildcard.outputs.changed }}
