name: Editorconfig-Checker
description: Runs Editorconfig-Checker on files tracked by Git.
inputs:
  version:
    description: Editorconfig-Checker version to install
    required: false
    default: 3.3.0

runs:
  using: "composite"
  steps:
    - name: Cache Editorconfig-Checker binary
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/editorconfig-checker
        key: EditorConfig-Checker-${{ inputs.version }}
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Install
      shell: sh
      env:
        URL: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v${{ inputs.version }}/ec-linux-386.tar.gz
        TMP: ${{ runner.temp }}
      run: |
        curl -sSL "$URL" | tar -xz -C "$TMP" --strip-components=1
        cp "$TMP/ec-linux-386" /usr/local/bin/editorconfig-checker
    - name: Run Editorconfig-Checker
      shell: bash
      run: |
        git ls-files -z | xargs -0 editorconfig-checker
