name: 'markdown-confluence'
description: 'Publish Markdown files to Confluence'
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  confluenceBaseUrl:
    description: 'The base URL of your Confluence instance, used for API calls and publishing content.'
  confluenceParentId:
    description: 'The ID of the parent page in Confluence where the Markdown files will be published as child pages.'
  atlassianUserName:
    description: 'Your Atlassian account''s username, required for authentication when interacting with Confluence.'
  atlassianApiToken:
    description: 'An API token generated for your Atlassian account, used for authentication when making API calls to Confluence.'
  folderToPublish:
    description: 'The folder you want to apply a default of "connie-publish: true" to.'
  contentRoot:
    description: 'The root path for published content on Confluence. This is used to tell the action where to look for Markdown files and content.'
  configFile:
    description: 'A configuration file containing additional settings and customizations for the publishing process.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CONFLUENCE_BASE_URL: ${{ inputs.confluenceBaseUrl }}
    CONFLUENCE_PARENT_ID: ${{ inputs.confluenceParentId }}
    ATLASSIAN_USERNAME: ${{ inputs.atlassianUserName }}
    ATLASSIAN_API_TOKEN: ${{ inputs.atlassianApiToken }}
    FOLDER_TO_PUBLISH: ${{ inputs.folderToPublish }}
    CONFLUENCE_CONTENT_ROOT: ${{ inputs.contentRoot }}
    CONFLUENCE_CONFIG_FILE: ${{ inputs.configFile }}
