name: Prettier
description: Run Prettier in check mode.
inputs:
  patterns:
    description: "The patterns to check with Prettier."
    required: false
    default: .
  version:
    description: The version of mkdocs-material to install.
    required: false
    default: 3.6.2
runs:
  using: "composite"
  steps:
    - name: Cache Prettier
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: prettier-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
    - name: Check Prettier
      shell: sh
      env:
        patterns: ${{ inputs.patterns }}
        version: ${{ inputs.version }}
      run: |
        npx "prettier@$version" "$patterns" --check
