name: Get repo name
description: Gets the repository name
outputs:
  repository_name:
    description: "The repository name"
    value: ${{ steps.get_repository_name.outputs.repository_name }}
runs:
  using: "composite"
  steps:
    - name: Get Repository Name
      id: get_repository_name
      shell: bash
      run: |
        REPO_NAME="$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo REPOSITORY_NAME="$REPO_NAME" >> "$GITHUB_ENV"
        echo "repository_name=$REPO_NAME" >> "$GITHUB_OUTPUT"
