name: Promote action in actions monorepo
description: |
  Given a monorepo composed of multiple action folders, deletes all other actions and moves all the 
  contents of the main action to the root of the repo.
inputs:
  action_name:
    description: 'The name of the action'
    required: true
  git_add:
    description: 'If true, persist changes in git'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Promote action
      id: promote
      shell: bash
      run: |
        ACTION_DIR="${{ inputs.action_name }}"
        if [[ ! -d "./$ACTION_DIR" ]]; then
          echo "The action folder $ACTION_DIR does not exist!"
          exit 1
        fi
        if [[ ! -f "./$ACTION_DIR/action.yml" ]]; then
          echo "The action folder $ACTION_DIR does not contain an action.yml file!"
          exit 1
        fi
        
        # Stash the action contents in a temporary folder
        TMP=$(mktemp -d)
        cp -a "./${ACTION_DIR}/"* "$TMP/"
        
        ALL_DIRS=($(ls -d */))
        # Remove all non-dotted directories from root
        
        for directory in "${ALL_DIRS[@]}"; do
          rm -rf "$directory"
        done
        
        # Restore the action contents to the root folder
        cp -a "$TMP/"* ./
        
        echo "Remaining files:"
        ls -al
        
        if [[ '${{ inputs.git_add }}' == 'true' ]]; then
          git add -A .
          git commit -m "Promoted action ${{ inputs.action_name }}"
        fi