name: Require Semver Label
description: "Ensures PR has exactly one semver label (major, minor, or patch)"
inputs:
  enforce:
    description: "Whether to fail upon missing semver label"
    default: "true"
    required: false
  error-message:
    description: "Message to echo upon failure"
    required: false
    default: "PR must have exactly one of the following labels: major, minor, patch"
runs:
  using: "composite"
  steps:
    - name: Get labels
      id: label
      uses: smartlyio/github-actions@get-labels-v1

    - name: Check for major label
      id: major
      uses: smartlyio/github-actions@require-label-v1
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "major"
        error-message: ${{ inputs.error-message }}

    - name: Check for minor label
      id: minor
      uses: smartlyio/github-actions@require-label-v1
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "minor"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.major.outputs.match }}

    - name: Check for patch label
      id: patch
      uses: smartlyio/github-actions@require-label-v1
      with:
        labels: ${{ steps.label.outputs.names }}
        name: "patch"
        error-message: ${{ inputs.error-message }}
        fail-on-match: ${{ steps.minor.outputs.match == 'true' || steps.major.outputs.match == 'true' }}

    - if: ${{ steps.major.outputs.match == 'false' && steps.minor.outputs.match == 'false' && steps.patch.outputs.match == 'false' }}
      id: fail
      name: Fail if no semver label matched
      shell: sh
      env:
        ERROR_MESSAGE: ${{ inputs.error-message }}
        ENFORCE: ${{ inputs.enforce }}
      run: |
        if [ "$ENFORCE" = "true" ]; then
          echo "Error: $ERROR_MESSAGE"
          exit 1
        else
          echo "skipped=true" >> "$GITHUB_OUTPUT"
        fi

    # This is not baked into output value to avoid falsely setting release type if a step fails
    - if: steps.fail.outputs.skipped != 'true'
      name: Set output
      id: release
      shell: sh
      run: |
        echo "type=${{ steps.major.outputs.match == 'true' && 'major' || steps.minor.outputs.match == 'true' && 'minor' || steps.patch.outputs.match == 'true' && 'patch' }}" >> "$GITHUB_OUTPUT"
outputs:
  bump:
    description: "The type of semver bump to be applied"
    value: ${{ steps.release.outputs.type }}
