name: Auto tag new actions

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, closed]

jobs:
  find_changes:
    name: "Find changed directories that need tagging"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
      matrix_empty: ${{ steps.get-matrix.outputs.matrix_empty }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: get-matrix
        uses: smartlyio/find-changes-action@v1
        with:
          directory_containing: action.yml

  create_tag:
    name: "Create tags"
    runs-on: ubuntu-20.04
    needs: find_changes
    if: needs.find_changes.outputs.matrix_empty == 'false' && github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.find_changes.outputs.matrix).directory }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: "${{github.action_path}}/../auto-tagger"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "${{ matrix.directory }}-"
