name: Test setup-ruby

on:
  pull_request:
    branches: [ master ]
    paths:
      - setup-ruby/**
      - _testing/setup-ruby/**

jobs:
  test:
    name: setup-ruby ${{ matrix.os }}/${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-11, macos-12 ]
        version: [ '2.7', '3.0', '3.1', '3.2' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: _actions
      - run: |
          cp -R ./_actions/_testing/setup-ruby/* .
      - uses: ./_actions/setup-ruby
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: 'true'

  ### This test is commented out. GitHub runners will fail on installing ruby via brew
  ### because of other broken dependencies in the brew update/upgrade process
  #  test-custom-wrapper:
  #    name: setup-ruby (wrap) ${{ matrix.os }}/${{ matrix.version }}
  #    strategy:
  #      fail-fast: false
  #      matrix:
  #        os: [ macos-11, macos-12 ]
  #        version: [ '2.7', '3.0', '3.1', '3.2' ]
  #    runs-on: ${{ matrix.os }}
  #    steps:
  #      - uses: actions/checkout@v3
  #        with:
  #          path: _actions
  #      - run: |
  #          cp -R ./_actions/_testing/setup-ruby/* .
  #      - uses: ./_actions/setup-ruby
  #        with:
  #          ruby-version: ${{ matrix.version }}
  #          force-custom-macos-install: 'true'