name: Test calculate-incremental-tag

on:
  pull_request:
    branches: [ master ]
    paths:
      - calculate-incremental-tag/**

jobs:
  test:
    name: calculate-incremental-tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: create_tag
        uses: ./calculate-incremental-tag
      - run: |
          echo "New tag: ${{ steps.create_tag.outputs.tag }}"
