name: Require Label
description: "Ensures PR has the specified label"
inputs:
  labels:
    description: "JSON array of labels from the get-labels action"
    required: true
  name:
    description: "The label name to check for"
    required: true
  error-message:
    description: "Message to echo upon failure"
    required: true
  fail-on-match:
    description: "Fail if name is included in labels"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Check for label
      id: label
      shell: sh
      env:
        LABELS: ${{ inputs.labels }}
        NAME: ${{ inputs.name }}
        ERROR_MESSAGE: ${{ inputs.error-message }}
        FAIL_ON_MATCH: ${{ inputs.fail-on-match }}
      run: |
        MATCH=$(echo "$LABELS" | jq -r "contains([\"$NAME\"])")
        echo "$NAME=$MATCH"
        echo "match=$MATCH" >> "$GITHUB_OUTPUT"

        if [ "$MATCH" = "true" ] && [ "$FAIL_ON_MATCH" != "false" ]; then
          echo "Error: $ERROR_MESSAGE"
          exit 1
        fi
outputs:
  match:
    description: "Whether name matched one of the labels (true/false)"
    value: ${{ steps.label.outputs.match }}
